const breakpoints = require('./src/breakpoints');
const {
  xxs,
  xs,
  tabletSm,
  tabletMd,
  tabletLg,
  tabletXxl,
  tabletXl,
  desktop,
  desktopXl,
  desktopXxl,
} = breakpoints;

module.exports = {
  darkMode: 'class',
  content: ['./src/components/**/*.{js,jsx,ts,tsx,css}'],
  separator: '|',
  theme: {
    extend: {
      colors: {
        blue: '#008fff',
        'blue-ada': 'var(--blue-ada)',
        'blue-dark': '#1b66e7',
        green: 'var(--green)',
        red: 'var(--red)',
        'green-chart': '#19b682',
        'red-chart': '#fe433d',
        'white-2': '#f8f8fb',
        charcoal: 'var(--charcoal)',
        'charcoal-darker': '#1c1c1e',
        'charcoal-darker-2': '#252527',
        'dark-red': '#cf0c1c',
        'primary-background': 'var(--primary-background)',
        'secondary-background': 'var(--secondary-background)',
        'tertiary-background': 'var(--tertiary-background)',
        'watchlist-background': 'var(--watchlist-background)',
        'dark-background': 'var(--dark-background)',
        'sitenav-login-background': 'var(--sitenav-login-background)',
        'tag-background': 'var(--tag-background)',
        'sidebar-background': 'var(--sidebar-background)',
        'mobile-nav-header-background': 'var(--mobile-nav-header-background)',
        'nav-sidebar-mobile-background': 'var(--nav-sidebar-mobile-background)',
        'nav-sidebar-tablet-background': 'var(--nav-sidebar-tablet-background)',
        'top-banner-background': 'var(--top-banner-background)',
        'emphasized-tab-background': 'var(--emphasized-tab-background)',

        'primary-text': 'var(--primary-text)',
        'secondary-text': 'var(--secondary-text)',
        'tertiary-text': 'var(--tertiary-text)',
        'light-text': 'var(--light-text)',
        'sitenav-text': 'var(--sitenav-text)',
        'tag-text': 'var(--tag-text)',
        'icon-text': 'var(--icon-text)',
        'stream-text': 'var(--stream-text)',

        'primary-hairline': 'var(--primary-hairline)',
        'secondary-hairline': 'var(--secondary-hairline)',

        'primary-border': 'var(--primary-border)',
        'secondary-border': 'var(--secondary-border)',
        'tertiary-border': 'var(--tertiary-border)',
        'stream-border': 'var(--stream-border)',
        'sitenav-border': 'var(--sitenav-border)',
        'sitenav-tablet-border': 'var(--sitenav-tablet-border)',
        'light-border': 'var(--light-border)',
        'divider-border': 'var(--divider-border)',

        'primary-hover': 'var(--primary-hover)',
        'primary-selected': 'var(--primary-selected)',
        'secondary-selected': 'var(--secondary-selected)',

        'primary-button-background': 'var(--primary-button-background)',
        'primary-button-text': 'var(--primary-button-text)',
        'primary-button-hover': 'var(--primary-button-hover)',
        'primary-button-hover-text': 'var(--primary-button-hover-text)',
        'primary-button-disabled': 'var(--primary-button-disabled)',
        'primary-button-disabled-text': 'var(--primary-button-disabled-text)',
        'secondary-button-background': 'var(--secondary-button-background)',
        'secondary-button-text': 'var(--secondary-button-text)',
        'secondary-button-hover': 'var(--secondary-button-hover)',
        'secondary-button-hover-text': 'var(--secondary-button-hover-text)',
        'secondary-button-disabled': 'var(--secondary-button-disabled)',
        'secondary-button-disabled-text':
          'var(--secondary-button-disabled-text)',
        'secondary-button-border': 'var(--secondary-button-border)',
        'watch-button-background': 'var(--watch-button-background)',
        'watch-button-hover': 'var(--watch-button-hover)',
        'databox-background-hover': 'var(--databox-background-hover)',

        'overlap-background': 'var(--overlap-background)',

        'grey-1': '#f6f6f6',
        'grey-2': '#edf0f4',
        'grey-4': '#e8e9eb',
        'grey-6': '#d4d6da',
        'grey-7': '#cecfd5',
        'grey-9': '#9c9ea5',

        /* iOS light greys */
        'light-grey': '#8e8e93',
        'light-grey-1': '#767676',
        'light-grey-2': '#aeaeb2',
        'light-grey-3': '#c7c7cc',
        'light-grey-4': '#d1d1d6',
        'light-grey-5': '#e5e5ea',
        'light-grey-6': '#f2f2f7',
        'light-grey-7': '#d1d1d6',
        'light-grey-8': '#dee0e3',
        'light-grey-10': '#8e8e93',
        'light-grey-11': '#c7c7cc',

        'light-grey-5-rgba-40': 'rgba(229, 229, 234, 0.4)',
        'light-grey-5-rgba-75': 'rgba(229, 229, 234, 0.75)',
        'light-grey-6-rgba-40': 'rgba(242, 242, 247, 0.4)',

        'legacy-blue': '#218dff',
        'legacy-blue-1': '#1c73e4',
        'legacy-blue-2': '#69c4ff',
        'legacy-blue-3': '#dbeffc',
        'legacy-bright-sky-blue': '#00baff',
        'legacy-light-blue-bg': 'var(--legacy-light-blue-bg)',
        'legacy-green-4': '#62d7b0',
        'legacy-green-5': 'var(--legacy-green-5)',
        'legacy-dark-green-text': 'rgb(19, 206, 111)',
        'legacy-gray-2': '#d7d9d',
        'legacy-gray-4': '#f9fbfe',
        'legacy-gray-5': '#f6f6fa',
        'legacy-white-four': '#f8f8f8',

        /* iOS dark greys */
        'dark-grey': '#8e8e93',
        'dark-grey-2': '#636366',
        'dark-grey-3': '#48484a',
        'dark-grey-4': '#3a3a3c',
        'dark-grey-5': '#2c2c2e',
        'dark-grey-6': '#020202',
      },
      boxShadow: {
        1: '0 7px 12px 0 rgba(0, 0, 0, 0.08)',
      },
      margin: {
        1.25: '0.3125rem',
      },
      borderWidth: {
        DEFAULT: '1px',
        3: '3px',
        5: '5px',
      },
      fontSize: {
        xxs: ['0.625rem', { lineHeight: '0.75rem' }],
      },
      width: {
        25: '6.25rem',
      },
      height: {
        25: '6.25rem',
      },
      padding: {
        1.25: '0.3125rem',
        13: '3.75rem',
        18: '4.5rem',
      },
      zIndex: {
        1: '1',
        2: '2',
        3: '3',
        25: '25',
      },
      opacity: {
        1: '0.01',
        2: '0.02',
        3: '0.03',
      },
    },
    screens: {
      xs: { min: `${xs}px` },
      'xxs-down': { max: `${xxs - 1}px` },
      'xs-down': { max: `${xs - 1}px` },
      'tabletSm-down': { max: `${tabletSm - 1}px` },
      'tabletSm-up': { min: `${tabletSm}px`, max: `${tabletMd - 1}px` },
      'tabletMd-down': { max: `${tabletMd - 1}px` },
      'tabletMd-up': { min: `${tabletMd}px`, max: `${tabletXl - 1}px` },
      'tabletXl-down': { max: `${tabletXl - 1}px` },
      'desktopXl-down': { max: `${desktopXl - 1}px` },
      tabletSm: `${tabletSm}px`,
      tabletMd: `${tabletMd}px`,
      tabletLg: `${tabletLg}px`,
      tabletXl: `${tabletXl}px`,
      tabletXxl: `${tabletXxl}px`,
      desktop: `${desktop}px`,
      desktopXl: `${desktopXl}px`,
      desktopXxl: `${desktopXxl}px`,
    },
  },
  variants: {
    extend: {
      borderWidth: ['first', 'last', 'dark'],
      borderRadius: ['first', 'last', 'dark'],
      margin: ['first', 'last'],
    },
  },
};
