import { useMediaQuery } from 'react-responsive';
export declare function useIsXs(): boolean;
export declare function useIsTabletSm(): boolean;
export declare function useIsTabletSmUp(): boolean;
export declare function useIsTabletMd(): boolean;
export declare function useIsTabletMdUp(): boolean;
export declare function useIsTabletLg(): boolean;
export declare function useIsTabletLgUp(): boolean;
export declare function useIsTabletRangeSm(): boolean;
export declare function useIsTabletRangeMd(): boolean;
export declare function useIsTabletRangeMdX(): boolean;
export declare function useIsTabletXl(): boolean;
export declare function useIsTabletXxl(): boolean;
export declare function useIsTabletXxlUp(): boolean;
export declare function useIsDesktop(): boolean;
export declare function useIsDesktopUp(): boolean;
export declare function useIsDesktopXlUp(): boolean;
export default useMediaQuery;
