export const container: string;
export const containerCompact: string;
export const mobile: string;
export const title: string;
export const titleDefault: string;
export const titleText: string;
export const titleCompact: string;
export const titleMobileNav: string;
export const icon: string;
export const iconDefault: string;
interface Namespace {
  container: string;
  containerCompact: string;
  'container-compact': string;
  'container-default': string;
  'container-mobile-nav': string;
  mobile: string;
  title: string;
  titleDefault: string;
  'title-default': string;
  titleText: string;
  titleCompact: string;
  'title-compact': string;
  titleMobileNav: string;
  'title-mobile-nav': string;
  icon: string;
  iconDefault: string;
  'icon-default': string;
  'icon-compact': string;
  'icon-mobile-nav': string;
}
declare const cardModule: Namespace;
export default cardModule;
